CREATE TABLE `tasksdb`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(130) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`));

--clausula like
--%a termina con a
--a% comienza con a
--%unu% dentro de la cadena hay un unu
select * from tasks where title like '%e';

--clausula betwen


/*
use repasocrud;
show tables;
describe personajes;
select * from personajes;
insert into personajes values ('crash', 'un zorro muy perrón', 'personaje principal');
insert into personajes (nombre) values ('pepe');

create database tasksdb;

use tasksdb;
show tables;
insert into tasks values (1, 'task 1', 'A description one');
insert into tasks values (2, 'task 2', 'A description two');
insert into tasks values (2, 'task 2', 'A description two');

alter table tasks AUTO_INCREMENT=1;

describe empleado;
delete from tasks where id =6
select * from empleado;
select * from tasks;
insert into empleados values



-- MySQL Script generated by MySQL Workbench
-- Fri Mar 24 18:59:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Gestick`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gestick` (
  `idGestick` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Contrasenna` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGestick`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL,
  `AdNombre` VARCHAR(45) NOT NULL,
  `AdAppat` VARCHAR(45) NOT NULL,
  `AdApmat` VARCHAR(45) NOT NULL,
  `AdContrasenna` VARCHAR(45) NOT NULL,
  `Gestick_idGestick` INT NOT NULL,
  `Aactivo` TINYINT NOT NULL,
  PRIMARY KEY (`idAdmin`, `Gestick_idGestick`),
  UNIQUE INDEX `idAdmin_UNIQUE` (`idAdmin` ASC) VISIBLE,
  INDEX `fk_Admin_Gestick1_idx` (`Gestick_idGestick` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_Gestick1`
    FOREIGN KEY (`Gestick_idGestick`)
    REFERENCES `mydb`.`Gestick` (`idGestick`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marca` (
  `idMarca` INT NOT NULL,
  `MarNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `CatNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `PrNombre` VARCHAR(45) NOT NULL,
  `PrPrecio` VARCHAR(45) NOT NULL,
  `PrExistencias` INT(100) NOT NULL,
  `PrDescripcion` VARCHAR(45) NULL,
  `Admin_idAdmin` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `Pcodigo` INT NOT NULL,
  PRIMARY KEY (`idProductos`, `Admin_idAdmin`, `Marca_idMarca`, `Categoria_idCategoria`),
  UNIQUE INDEX `idProductos_UNIQUE` (`idProductos` ASC) VISIBLE,
  INDEX `fk_Productos_Admin_idx` (`Admin_idAdmin` ASC) VISIBLE,
  INDEX `fk_Productos_Marca1_idx` (`Marca_idMarca` ASC) VISIBLE,
  INDEX `fk_Productos_Categoria1_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Admin`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `mydb`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Imagen Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Imagen Producto` (
  `idImagen Producto` INT NOT NULL,
  `ImProURL` LONGTEXT NOT NULL,
  `tipoImagenPro` VARCHAR(45) NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Productos_Admin_idAdmin` INT NOT NULL,
  PRIMARY KEY (`idImagen Producto`, `Productos_idProductos`, `Productos_Admin_idAdmin`),
  INDEX `fk_Imagen Producto_Productos1_idx` (`Productos_idProductos` ASC, `Productos_Admin_idAdmin` ASC) VISIBLE,
  UNIQUE INDEX `idImagen Producto_UNIQUE` (`idImagen Producto` ASC) VISIBLE,
  CONSTRAINT `fk_Imagen Producto_Productos1`
    FOREIGN KEY (`Productos_idProductos` , `Productos_Admin_idAdmin`)
    REFERENCES `mydb`.`Productos` (`idProductos` , `Admin_idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eimagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eimagen` (
  `idEimagen` INT NOT NULL,
  `Eurl` LONGTEXT NOT NULL,
  `Etipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEimagen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `EmNombre` VARCHAR(45) NOT NULL,
  `EmApat` VARCHAR(45) NOT NULL,
  `EmAmat` VARCHAR(45) NOT NULL,
  `EmContrasenna` VARCHAR(50) NOT NULL,
  `Admin_idAdmin` INT NOT NULL,
  `Eimagen_idEimagen` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`, `Admin_idAdmin`, `Eimagen_idEimagen`),
  INDEX `fk_Empleado_Admin1_idx` (`Admin_idAdmin` ASC) VISIBLE,
  INDEX `fk_Empleado_Eimagen1_idx` (`Eimagen_idEimagen` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Eimagen1`
    FOREIGN KEY (`Eimagen_idEimagen`)
    REFERENCES `mydb`.`Eimagen` (`idEimagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrito` (
  `idCarrito` INT NOT NULL AUTO_INCREMENT,
  `CarFecha` DATE NOT NULL,
  `Total` FLOAT NOT NULL,
  `idEmpleadoC` INT NOT NULL,
  PRIMARY KEY (`idCarrito`),
  UNIQUE INDEX `idCarrito_UNIQUE` (`idCarrito` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos_has_Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos_has_Carrito` (
  `Productos_idProductos` INT NOT NULL,
  `Productos_Admin_idAdmin` INT NOT NULL,
  `Productos_Marca_idMarca` INT NOT NULL,
  `Productos_Categoria_idCategoria` INT NOT NULL,
  `Carrito_idCarrito` INT NOT NULL,
  `ProVendidos` INT NOT NULL,
  PRIMARY KEY (`Productos_idProductos`, `Productos_Admin_idAdmin`, `Productos_Marca_idMarca`, `Productos_Categoria_idCategoria`, `Carrito_idCarrito`),
  INDEX `fk_Productos_has_Carrito_Carrito1_idx` (`Carrito_idCarrito` ASC) VISIBLE,
  INDEX `fk_Productos_has_Carrito_Productos1_idx` (`Productos_idProductos` ASC, `Productos_Admin_idAdmin` ASC, `Productos_Marca_idMarca` ASC, `Productos_Categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_has_Carrito_Productos1`
    FOREIGN KEY (`Productos_idProductos` , `Productos_Admin_idAdmin` , `Productos_Marca_idMarca` , `Productos_Categoria_idCategoria`)
    REFERENCES `mydb`.`Productos` (`idProductos` , `Admin_idAdmin` , `Marca_idMarca` , `Categoria_idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Carrito_Carrito1`
    FOREIGN KEY (`Carrito_idCarrito`)
    REFERENCES `mydb`.`Carrito` (`idCarrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





*/